create database details;
use details;
create table student (id  int,name varchar(10),address varchar(30),maths int(3),physics int(3),cs int(3),total int(4));
select* from student;
insert into student values(1,'adwaith','mavoor',98,90,92,280);
insert into student values(2,'varna','kommeri',90,80,80,250);
insert into student values(3,'rilu','eranjikkal',60,60,60,180);
insert into student values(4,'saniga','nadakkav',50,50,52,150);
insert into student values(5,'avinash','med clg',52,52,52,156);
insert into student values(6,'niranjan','mavoor',98,90,92,280);
insert into student values(7,'sree','kommeri',90,80,80,250);
insert into student values(8,'abhinav','pottammal',60,60,60,180);
insert into student values(9,'aswani','nadakkav',50,50,52,150);
insert into student values(10,'ajay','med clg',52,52,52,156);
insert into student values(11,'vijay','kozhikode',52,52,52,156);
select * from student;
select id,name from student;
select id,name from student where total>250;
select name from student where address='kozhikode';
insert into student values(12,'varun','kozhikode',59,52,52,162);
insert into student values(13,'sarang','kozhikode',52,52,52,156);
insert into student values(14,'reema','kozhikode',52,52,52,null);

update student set total=250 where name='varun';
delete from student where name='sarang';
SELECT total,name from student where total is null;
update student set name='adwaith' where name='robin';
select * from student where address="kozhikode" or address="mavoor";
ALTER TABLE student ADD COLUMN dept VARCHAR(10);
update student set dept="mca" where name ="adwaith";
update student set dept="mca" where name ="varna";
update student set dept="mca" where name ="rilu";
update student set dept="mca" where name ="saniga";
update student set dept="mca" where name ="avinash";
update student set dept="mca" where name ="niranjan";
update student set dept="mca" where name ="sree";
update student set dept="mca" where name ="abhinav";
update student set dept="mca" where name ="aswani";
update student set dept="mca" where name ="ajay";
update student set dept="mca" where name ="vijay";
update student set dept="mca" where name ="varun";
update student set dept="eng" where name ="reema";
select * from student;
select name,dept from student order by name desc; 
insert into student values(15,'siva',null,52,52,52,156,"mca");
SELECT name from student where address is null;
select max(total) from student;
select min(maths) from student;
select avg(cs) from student;
select sum(physics) from student;
select name,dept from student where dept like '%g';
select name from student where name like 'a%';
alter table student drop total;
ALTER TABLE student ADD COLUMN totalmark int(3);
update student set totalmark =maths+physics+cs;
select * from student;
ALTER TABLE student ADD COLUMN age int(2);
update student set age=23 where name ="adwaith";
update student set age=18 where name ="varna";
update student set age=16 where name ="rilu";
update student set age=20 where name ="saniga";
update student set age=21 where name ="avinash";
update student set age=23 where name ="niranjan";
update student set age=24 where name ="sree";
update student set age=19 where name ="abhinav";
update student set age=21 where name ="aswani";
update student set age=20 where name ="ajay";
update student set age=18 where name ="vijay";
update student set age=18 where name ="varun";
update student set age=22 where name ="reema";
update student set age=22 where name ="siva";
select * from student;




